### ISSUE TITLE
Weird version values in Tracker Card

### ISSUE THREAD

**Issue by quantummobile** [thomasloven/lovelace-card-tools#12]
Hi,

any idea why version values of Card Tools and Layout Card are represented by some kind of string instead of regular x.x.x pattern with numbers?

![screenshot 2019-02-21 at 21 09 44](https://user-images.githubusercontent.com/47085307/53195199-d959c000-361d-11e9-8bc2-909fc83d19ea.png)

**Comment by iantrich** [comment]
because they are based on commits, not releases for thomas' stuff
