### ISSUE TITLE
Uncaught TypeError: cardTools.deviceID is not a function

### ISSUE THREAD

**Issue by Skeletorjus** [thomasloven/lovelace-card-tools#15]
browser_commander throws this error:
`https://000.000.000.000:8123/customcards/browser-commander.js:58:42 Uncaught TypeError: cardTools.deviceID is not a function`

Seems to have been introduced in 0.4 as changing this line back fixed the error: https://github.com/thomasloven/lovelace-card-tools/commit/6e12de21560c3536e5c1778cbe9e62c195658e0c#diff-125a148354939c6ea9dbf6eaedf8d775L181

**Comment by thomasloven** [comment]
Browser-commander has been updated to fix this problem.
