### ISSUE TITLE
TypeError: null is not an object ...

### ISSUE THREAD

**Issue by septeven** [thomasloven/lovelace-card-tools#16]
Hi,
Since a while (may be one or two version of Hassio), I got those error multiple times a day. Didn't find a way to troubleshoot them though, so I can't tell when they occur. I am running 0.88.1.

Here is the error :

`http://hassio.local:8123/customcards/github/thomasloven/card-tools.js?track=true:68:53 TypeError: null is not an object (near '..."ha-panel-lovelace")...')`

Hopefully that'll help.

**Comment by thomasloven** [comment]
Hm... The only way I can imagine this happning is if you open a more-info dialog outside of lovelace without reloading the page.

That could happen e.g. if you go to `/dev-state` and open the info for an entity or if you go to `/states` using something with `tap_action: navigate` and then click something there.
Could this be what happened?

**Comment by septeven** [comment]
So I just checked it out.
Yes, I notice that the error is occurring each time I open the info for an entity in the States UI page and same thing in the dev-state page - any entity I click on that opens an info popup will trigger the error.

**Comment by thomasloven** [comment]
Great! Then I think I know how to fix it.

**Comment by thomasloven** [comment]
There we go. Update both card-tools and popup-card.

**Comment by septeven** [comment]
Yes that fixed the problem - Thanks Thomas!

**Comment by septeven** [comment]
Hey Thomas, got the same errors triggered again yesterday, 18 times...

**Comment by thomasloven** [comment]
Did you clear the cache on all your devices and all open tabs?

**Comment by septeven** [comment]
Hmm not really - that might be the cause - I'll let you know if that happens again, so far it has not
