### ISSUE TITLE
Throwing an error on Fully Kiosk Browser on Fire 7 Tablet

### ISSUE THREAD

**Issue by pjv** [thomasloven/lovelace-card-tools#2]
I've just updated to HA version `.84.3` and then updated layout-card to `bd7e5a` which now requires card-tools, so I installed card-tools and it's at `445b68`.

Restarted HA and cleared all caches on all browsers and everything is working fine everywhere except for one place: the view where I am using layout-card is throwing an error on the Fully Kiosk Browser in my Amazon Fire 7 tablet. In the browser it's giving me the "Can't find card-tools." error. In HA logs, I get this:

`2018-12-18 08:22:52 ERROR (MainThread) [frontend.js.es5.201812111] http://redacted:8123/local/custom-lovelace/card-tools.js?v=445b68:140:50 Uncaught SyntaxError: Unexpected token ...`

The view works fine everywhere else, including (significantly) in the Silk browser on the same Fire 7 tablet. In other words, it doesn't seem to be a webview issue because I believe that Fully is using the same webview as Silk on the tablet.

I don't know how to see anything more detailed for JS errors in Fully, so I'm stuck in even figuring out what's going on. 

Any suggestions?

ping @thomasloven

**Comment by strlng** [comment]
I am seeing the same error on a Raspberry Pi running Raspbian and Chromium web browser. In both kiosk mode and running normally. Works fine on macOS in Chrome, Safari, and Firefox.

**Comment by thomasloven** [comment]
I think this should be fixed now.

**Comment by thomasloven** [comment]
That's what I get for trying to use the latest features of javascript.

Try now.

**Comment by strlng** [comment]
That did it, fixed!

**Comment by pjv** [comment]
thanks for the fix 👍
