### ISSUE TITLE
card-tools.js:19:12 Uncaught TypeError:. Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by TheMrg** [thomasloven/lovelace-card-tools#22]
We get this:
[frontend.js.latest.201903210] local/card-tools.js:19:12 Uncaught TypeError:.
Cannot convert undefined or null to object

But not on all devices. Only on Google Android Chrome.

**Comment by TheMrg** [comment]
Ok, seems it is a cache issue.
How can we say that the browser should noch cache local/card-tools.js ?

**Comment by thomasloven** [comment]
Easiest way (which always works with mobile browsers as well) is to use a version number, as decribed here: https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins
