### ISSUE TITLE
Question: Can I use the deviceID in a conditional card?

### ISSUE THREAD

**Issue by vandalon** [thomasloven/lovelace-card-tools#24]
Hi,

Can I use the deviceID in a conditional card so that for example I can show a specific link/icon on a specific device?

My use case:

Having a icon/button to press that opens the sonos app on android running HA on fully-kiosk, on a tablet, on my wall.

**Comment by iantrich** [comment]
How is this related to card-tools? Not sure how you could get an app to launch, perhaps with Tasker; regardless check out https://github.com/thomasloven/lovelace-state-switch

**Comment by vandalon** [comment]
I figured because card tools get the deviceID :)

**Comment by iantrich** [comment]
card-tools isn't an actual card though. It's a set of utilities to be used by other custom card developers.

**Comment by vandalon** [comment]
I understand, I figured you would be the right person to ask :) thanks anyhow!

**Comment by thomasloven** [comment]
Thank you, @iantrich!
