### ISSUE TITLE
Remove the only release to make it work with HACS

### ISSUE THREAD

**Issue by RomRider** [thomasloven/lovelace-card-tools#27]
Hey,

Switching to [hacs](https://github.com/custom-components/hacs) instead of `custom_updater` is failing for this card as there is a release in the repo and actually `hacs` prefers the release over the master branch in your case.
Since you're not using releases, could you please remove it? :)

Thanks!

**Comment by thomasloven** [comment]
Made a new release instead. I plan to start using them.

... and also to slowly deprecate card-tools...
