### ISSUE TITLE
Cannot concat string with entity state

### ISSUE THREAD

**Issue by guillaumelamirand** [thomasloven/lovelace-card-tools#35]
Hi,

I am trying to display either an entity state following by a string or nothing depending on another entity state. I am using this template :

`[[ if(binary_sensor.monitoring_ha_updater.state == "on", sensor.monitoring_potential_breaking_changes.state "changes" ,"") ]]`

On lovelace side it displays "undefined" as a result instead of "0 changes". I tried using +,++, . to concat them without success.

Thanks for helping.

**Comment by thomasloven** [comment]
There's no way to do this, and I have no interest in maintaining the old style templates when there are better alternatives.
Either put two templates after each other, or convert your plugin to use the new template functions.

**Comment by guillaumelamirand** [comment]
I am not using it in my own plug-in just trying to use the template syntax. Could you give me more details about "better alternatives"?

**Comment by thomasloven** [comment]
If you're not using card-tools for your own plugin, I suggest you instead raise this issue with the maintainer of the plugin you are using.

**Comment by thomasloven** [comment]
The better alternative is to use jinja2 templating, which is also supported by card-tools.

**Comment by guillaumelamirand** [comment]
> If you're not using card-tools for your own plugin, I suggest you instead raise this issue with the maintainer of the plugin you are using.

As the question was regarding the support of templating which you offer with your lib and not the plugin, I thought you were the best person to help me.

In the meantime, I used the following as workarround :

```
 [[ if(binary_sensor.monitoring_ha_updater.state == "on",
          sensor.monitoring_potential_breaking_changes.state, "") ]] [[
          if(binary_sensor.monitoring_ha_updater.state == "on", "changement(s)
          bloquant(s)", "") ]] 
```
