### ISSUE TITLE
Add to HACS

### ISSUE THREAD

**Issue by marksie1988** [thomasloven/lovelace-card-tools#36]
Please could this be added the the Home Assistant Community Store?

**Comment by thomasloven** [comment]
https://hacs.xyz/ (watch the gif)

**Comment by KennethLavrsen** [comment]
I am looking at the gif. I assume the animated gif that shows how to use HACS. That does not say anything about why your Card Tools repository is not to be found in HACS.

There are many other front end cards that depend on it so I really wonder why this one is not there. If you click on the + in HACS and search for card tools it does not show up. 

Are you and the maintainer of HACS not good friends or ...?

**Comment by KennethLavrsen** [comment]
It is strange. I searched for both "card" and "tools" and it did not show up.

Then I tried to add the URL for the git-hub for this repo and got the message it was already there. Then I added my comment above on this bug report.

And after I went back and tried again looking for tools and then it popped up. It was like the attempt to add the repo changed something in HACS. In case someone sees this you may want to try the same

**Comment by mdrichardson** [comment]
I was having the same confusion. Turns out, you don't have to add this as a _custom_ repository.

To install via HACS:

1. Go to Community > Frontend
2. In the bottom-right, click "+ Explore & Download Repositories"
3. Search "card-tools" and click it
4. Click "Download"
