### ISSUE TITLE
card-tools/popup.js?:28:14 Uncaught TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by ercsey** [thomasloven/lovelace-card-tools#38]
I'm using browser_mod (version 13) to show a popup when clicking a button card. Recently I'm getting this error and no popup shows up. After refreshing the page the problem disappears.
I'm using Hass.io 0.101.2 on Ubuntu with docker.

> Wed Nov 06 2019 21:38:18 GMT+0200 (Eastern European Standard Time)
> webpack:////card-tools/popup.js?:28:14 Uncaught TypeError: Cannot read property 'close' of undefined

Any idea what causing it? Thank you.

**Comment by thomasloven** [comment]
Please try version 13.1

**Comment by ercsey** [comment]
I've realized what causing the problem. If multiple tabs are open on the same device when calling the browser_mod to open a popup it cannot decide on which tab to open it. Many times it opens on a different tab. Sorry for the false alarm.
