### ISSUE TITLE
Use with custom:secondaryinfo-entity-row cause error

### ISSUE THREAD

**Issue by cepxuo** [thomasloven/lovelace-card-tools#41]
Upgrading to version 8 causes "Custom element doesn't exist: hui-default-entity-row." error in cards with type: custom:secondaryinfo-entity-row

Needed to roll back to 2.3  version.

**Comment by iantrich** [comment]
show your config, it likely got updated and you just have to edit it

**Comment by VDRainer** [comment]
Card-tools or secondaryinfo-entity-row, that's the question. https://github.com/home-assistant/home-assistant-polymer/issues/4670#issuecomment-580426121

**Comment by iantrich** [comment]
Yeah card tools I believe

**Comment by iantrich** [comment]
I suspect this is the issue here: https://github.com/thomasloven/lovelace-card-tools/blob/master/src/lovelace-element.js#L106

**Comment by iantrich** [comment]
I'm actually seeing the same thing on my restriction-card. Will take a look tonight to see if I can pinpoint. Paulie did rewrite the base create functions

**Comment by cepxuo** [comment]
Sorry, that was secondaryinfo-entity-row bug, already fixed in updated version.
