### ISSUE TITLE
Why is card_tools not available in HACS???

### ISSUE THREAD

**Issue by DrJohnT** [thomasloven/lovelace-card-tools#43]
I added someone else's custom card to my Lovelace UI

```yaml
type: 'custom:search-card'
max_results: 10
```
but then I got the error
```
Can't find card_tools. See https://github.com/thomasloven/lovelace-card-tools
```

Of course, I added the card-tools module manually to my config. 

But why is card_tools not available in HACS??  
Seems rather bizarre!

**Comment by jcwillox** [comment]
It is currently available on HACS, just search for `card-tools`. 
https://hacs.xyz/docs/default_repositories

**Comment by DrJohnT** [comment]
Thanks.  Not sure why I did not spot it because I did look at the time.
