### ISSUE TITLE
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'Object(a.c)()._addCard')

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-tools#50]
<img width="798" alt="Schermafbeelding 2020-06-29 om 13 25 34" src="https://user-images.githubusercontent.com/33354141/86002762-1b182900-ba11-11ea-9470-f7a9f2a3b417.png">

showing on each view.
using HA 0.111.4 and card-tools version 10

thought it might have been the card picker issue mentioned by Bram here https://github.com/home-assistant/frontend/issues/6262#issuecomment-651051802 but he pointed me back here

**Comment by Mariusthvdb** [comment]
fwiw, I dont see this any longer, on 0.112.x
so closing.

**Comment by Mariusthvdb** [comment]
well, of course I shouldn't have posted that.... real sorry:

<img width="787" alt="Schermafbeelding 2020-07-05 om 15 17 04" src="https://user-images.githubusercontent.com/33354141/86533611-9aef3900-bed2-11ea-8b4e-e3dbbfaa75fa.png">

HA 112.2

**Comment by niemyjski** [comment]
I'm also seeing this error a lot as well as this one: 

```
TypeError: r.setConfig is not a function. (In 'r.setConfig({type:"error",error:e,origConfig:t})', 'r.setConfig' is undefined)
u — card-tools.js:1:6331
d — card-tools.js:1:6779
_createElement — secondaryinfo-entity-row.js:29
setConfig — secondaryinfo-entity-row.js:15
s — chunk.5cd6ebaa3e3e7e5d9059.js:12717
l — chunk.5cd6ebaa3e3e7e5d9059.js:12717
value — chunk.5cd6ebaa3e3e7e5d9059.js:9058
map
value — chunk.5cd6ebaa3e3e7e5d9059.js:8982
update — app.9108bd0a.js:1
performUpdate — app.9108bd0a.js:1
(anonymous function) — app.9108bd0a.js:1
asyncFunctionResume
[native code]
promiseReactionJobWithoutPromise
promiseReactionJob```

**Comment by KTibow** [comment]
And I'm getting what I think is also related:
```js
Uncaught (in promise) TypeError: Cannot read property '_addCard' of null
```
I used Chrome's built-in prettifier, and this is the cause:
```js
Object(a.c)()._addCard()
```

**Comment by KTibow** [comment]
Looks like if you get the straight code from master it was fixed, or at least the code that caused that error was fixed...
And @niemyjski it looks like this might actually be because of `secondaryinfo-entity-row` instead...

**Comment by Mariusthvdb** [comment]
closing, this has been goon for some time now.
