### ISSUE TITLE
Issue with 0.114.0b0

### ISSUE THREAD

**Issue by DavidFW1960** [thomasloven/lovelace-card-tools#54]
Hi Thomas.. loading card-tools causes lovelace to prompt to add a new card to the view when refreshing (and CTRL+R and CTRL+F5) in 0.114.0b0
Issue here for HA frontend https://github.com/home-assistant/frontend/issues/6526
I nailed it down to card-tools by adding card-tools to my dev machine - it started doing it immediately I loaded card-tools.

**Comment by DavidFW1960** [comment]
now I'm confused.. I added card-tools to a new VM and it's not doing it. (it's the only card on the new VM...)
I'll add card-mod now as well ?

**Comment by VDRainer** [comment]
Must be some combination with other cards.
If i remove card-tools from the resources the issue is gone.

**Comment by DavidFW1960** [comment]
Thomas just pushed an update for Card-Tools that fixes the issue @VDRainer
