### ISSUE TITLE
"card-tools" will not show on iOS app

### ISSUE THREAD

**Issue by hwikene** [thomasloven/lovelace-card-tools#7]
Hi! 
I cant get "card-tools" to work on my iPhone. If i open Lovelace in iOS app (1.5.0) i only get errors (see pictures)
Have also tried to open my HA in some browsers on my phone:
Firefox: not working
Chrome: not working
Safari: working ok
i also have this: 
```
frontend:
  javascript_version: latest
```
I am using HA 0.86.3 on NUC. 
Here is some examples: 
![1](https://user-images.githubusercontent.com/17985923/51834233-fa1e4680-22f9-11e9-9b72-bafe3475e445.png)
![2](https://user-images.githubusercontent.com/17985923/51834238-fc80a080-22f9-11e9-8fc5-65bf8ce97603.png)
![4 png](https://user-images.githubusercontent.com/17985923/51834329-3baef180-22fa-11e9-8879-649c1e5606d4.jpg)

**Comment by thomasloven** [comment]
Is this still a problem?
