### ISSUE TITLE
Rendering weblink as hyperlink

### ISSUE THREAD

**Issue by bruxy70** [thomasloven/lovelace-card-tools#9]
What do I need to change to make weblinks to show as hyperlink?
I am trying to use fold-entity-row to make a list of devices with their status via device_tracker or template sensor, and have custom-popup card with the weblink to the device. It works, except it shows the weblink as text and does not make hyperlink. Same when I add the weblink directly in the fold-entity-row.
I believe this is due to how lovelace-card-tool renders the weblink. But how do I change it to add the hyperlink?
(Earlier, I made a custom card where I have combined the device_tracker and weblink into one sensor, but as I am shitty developer it did not work well, and I love fold-entity-row with the custom-popup cards that would do the trick)

**Comment by thomasloven** [comment]
Can't reproduce. If this is still a problem, please provide a minimal working example.

**Comment by bruxy70** [comment]
Add this to config.yaml

> weblink:
>   entities:
>     - name: Test
>       url: http://192.168.1.1

Then this to your UI config:

> resources:
>   - type: js
>     url: /local/custom_ui/card-tools.js?v=1
>   - type: js
>     url: /local/custom_ui/fold-entity-row.js?v=1

and

> entities:
>   - head:
>       label: 'Test'
>       type: section
>     items:
>       - weblink.test
>     type: 'custom:fold-entity-row'
> title: Test
> type: entities

It will show the name, the URL, but the URL will not function as a hyperlink.

**Comment by thomasloven** [comment]
That's exactly how the built-in `entities` card handle a weblink entity.

```yaml
- type: entities
  entities:
    - weblink.test
```

That form of weblink is all but deprecated.
See https://www.home-assistant.io/lovelace/entities/#weblink
